package com.NovaInv;

import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import cpw.mods.fml.relauncher.Side;
import net.minecraft.util.EnumChatFormatting;
import org.apache.logging.log4j.Logger;
import cpw.mods.fml.common.FMLCommonHandler;
import net.minecraftforge.common.MinecraftForge;

@Mod(modid = "nova_inventory", version = "1.0", name = "Nova Inventory")
public class NovaInventory {
    public static final String MOD_ID = "nova_inventory";
    public static final String VERSION = "1.0";
    @Mod.Instance("nova_inventory")
    public static NovaInventory instance;
    public static Logger logger;
    public static final SimpleNetworkWrapper NETWORK = NetworkRegistry.INSTANCE.newSimpleChannel("NovaInv");

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        event.getModMetadata().autogenerated = false;
        event.getModMetadata().name = EnumChatFormatting.GOLD + "NovaInventory" + EnumChatFormatting.GOLD;
        event.getModMetadata().version = EnumChatFormatting.GOLD + "1.0";
        event.getModMetadata().credits = EnumChatFormatting.AQUA + " Wojak ";
        event.getModMetadata().url = EnumChatFormatting.GRAY + "";
        event.getModMetadata().description = EnumChatFormatting.GOLD + "A 1.7.10 mod that doubles the inventory size in the most seamless way possible.";
        instance = this;
        logger = event.getModLog();
        NovaInventory.instance = this;
        MinecraftForge.EVENT_BUS.register((Object)this);
        FMLCommonHandler.instance().bus().register((Object)this);
        MinecraftForge.TERRAIN_GEN_BUS.register((Object)this);
        MinecraftForge.ORE_GEN_BUS.register((Object)this);
        NETWORK.registerMessage(PacketInventoryPage.Handler.class, PacketInventoryPage.class, 0, Side.SERVER);

    }

    public static String modAddress() {
        return MOD_ID + ":";
    }
}
